#!/bin/bash

system_type=$(uname -s)

echo "--Starting Bootstrap Script--"

if [ "$system_type" = "Linux" ]; then
  echo "Linux Detected"
  
  # Install Apt Packages
  xargs -a <(awk '! /^ *(#|$)/' ./scripts/aptlist) -r -- sudo apt install -y

  #Cleaning up unused apt packages
  sudo apt autoremove -y

elif [ "$system_type" = "Darwin" ]; then
  echo "Mac Detected"

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  # Run homebrew bundle
  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  # Setup iTerm2
  if [ -d "$HOME/.config/iterm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.config/iterm2"
    defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
  fi

  # Setup Bitbar
  if [ -d "$HOME/bitbar" ]; then
    echo "Setting Bitbar Plugin Directory"
    defaults write com.matryer.BitBar pluginsDirectory "$HOME/bitbar"
  fi

  if [ ! -f "$HOME/.oh-my-zsh/oh-my-zsh.sh" ]; then
    echo "Installing Oh-My-Zsh"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    mv $HOME/.zshrc $HOME/.zshrc_new
    mv $HOME/.zshrc.pre-oh-my-zsh $HOME/.zshrc
  fi

  # Install ZSH Custom Plugins if not present
  echo "Installing any missing zsh plugins - Will not update"
  ZSH_CUSTOM=~/.oh-my-zsh/custom
  [ ! -d $ZSH_CUSTOM/themes/powerlevel10k ] && git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k

  [ ! -d $ZSH_CUSTOM/plugins/wakatime ] && git clone --depth=1 https://github.com/wbingli/zsh-wakatime.git $ZSH_CUSTOM/plugins/wakatime

  [ ! -d $ZSH_CUSTOM/plugins/zsh-autosuggestions ] && git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions

  [ ! -d $ZSH_CUSTOM/plugins/zsh-completions ] && git clone https://github.com/zsh-users/zsh-completions $ZSH_CUSTOM/plugins/zsh-completions

  # Mac Settings
  ${HOME}/.config/yadm/scripts/mac-settings.sh

else
  echo "No Bootstrap configuration for " $system_type

fi

