version: '3'

tasks:
  update:
    precondition:
      - test -d ~/config/NvChad
    cmds:
      - 
    silent: true
  install:
    preconditions:
      - ! test -d ~/.config/NvChad
    cmds:
      - git clone https://github.com/NvChad/NvChad --depth 1 && nvim

